package tor

import (
	"fmt"
	"strings"
	"tuxproxy/internal/config"
)

// BuildTorrc generates a hardened, zero-leak torrc configuration string
func BuildTorrc(cfg *config.Config, dataDir string, socksPort, httpPort, dnsPort, controlPort int) string {
	var sb strings.Builder

	sb.WriteString("# Auto-generated by TuxProxy - Strict OPSEC Tor configuration\n")
	sb.WriteString(fmt.Sprintf("DataDirectory %s\n", dataDir))
	sb.WriteString("AvoidDiskWrites 1\n")
	sb.WriteString("Log notice stdout\n\n")

	// Listener Ports with stream isolation
	sb.WriteString("# Local Proxy Listeners\n")
	sb.WriteString(fmt.Sprintf("SocksPort 127.0.0.1:%d IsolateDestAddr IsolateDestPort\n", socksPort))
	sb.WriteString(fmt.Sprintf("HTTPTunnelPort 127.0.0.1:%d IsolateDestAddr IsolateDestPort\n", httpPort))
	sb.WriteString(fmt.Sprintf("DNSPort 127.0.0.1:%d\n", dnsPort))
	sb.WriteString(fmt.Sprintf("ControlPort 127.0.0.1:%d\n\n", controlPort))

	// Privacy & Zero-Leak Hardening
	sb.WriteString("# OPSEC & Zero-Leak Hardening\n")
	if cfg.SafeLogging {
		sb.WriteString("SafeLogging 1\n")
	} else {
		sb.WriteString("SafeLogging 0\n")
	}

	if cfg.DisableIPv6 {
		// Prevent dual-stack IPv6 DNS or socket leaks
		sb.WriteString("ClientUseIPv6 0\n")
		sb.WriteString("ClientPreferIPv6ORPort 0\n")
	}

	// Geolocation & Exit Node routing
	country := strings.ToLower(strings.TrimSpace(cfg.ExitCountry))
	if country != "" && country != "any" {
		sb.WriteString("\n# Geo-IP Exit Node Enforcement\n")
		sb.WriteString(fmt.Sprintf("ExitNodes {%s}\n", country))
		if cfg.StrictNodes {
			sb.WriteString("StrictNodes 1\n")
		} else {
			sb.WriteString("StrictNodes 0\n")
		}
	}

	if strings.TrimSpace(cfg.ExcludeNodes) != "" {
		sb.WriteString(fmt.Sprintf("ExcludeNodes %s\n", strings.TrimSpace(cfg.ExcludeNodes)))
		sb.WriteString(fmt.Sprintf("ExcludeExitNodes %s\n", strings.TrimSpace(cfg.ExcludeNodes)))
	}

	if cfg.NumEntryGuards > 0 {
		sb.WriteString(fmt.Sprintf("NumEntryGuards %d\n", cfg.NumEntryGuards))
	}

	// Bridges and Pluggable Transports
	bridgeType := strings.ToLower(strings.TrimSpace(cfg.BridgeType))
	if bridgeType != "" && bridgeType != "none" {
		sb.WriteString("\n# Pluggable Transports & Anti-Censorship Bridges\n")
		sb.WriteString("UseBridges 1\n")

		switch bridgeType {
		case "snowflake":
			snowflakeBin := cfg.SnowflakePath
			if snowflakeBin == "" {
				snowflakeBin = "/usr/bin/snowflake-client"
			}
			brokerURL := cfg.SnowflakeURL
			if brokerURL == "" {
				brokerURL = "https://snowflake-broker.torproject.net/"
			}
			front := cfg.SnowflakeFront
			if front == "" {
				front = "www.google.com"
			}
			ampCache := cfg.SnowflakeAMPCache
			if ampCache == "" {
				ampCache = "https://cdn.ampproject.org/"
			}

			iceServers := "stun:stun.l.google.com:19302,stun:stun.voip.blackberry.com:3478"
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin snowflake exec %s -url %s -front %s -ampcache %s -ice %s\n",
				snowflakeBin, brokerURL, front, ampCache, iceServers))

			// Include standard Snowflake bridges
			for _, br := range config.DefaultSnowflakeBridges {
				sb.WriteString(fmt.Sprintf("%s\n", br))
			}
			// Append user custom bridges if provided
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
				}
			}

		case "obfs4":
			lyrebirdBin := cfg.LyrebirdPath
			if lyrebirdBin == "" {
				lyrebirdBin = "/home/djanki/.local/bin/lyrebird"
			}
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin obfs4 exec %s\n", lyrebirdBin))
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}

		case "webtunnel":
			webtunnelBin := cfg.WebTunnelPath
			if webtunnelBin == "" {
				webtunnelBin = "/usr/local/bin/webtunnel-client"
			}
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin webtunnel exec %s\n", webtunnelBin))
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}

		case "custom":
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}
		}
	}

	return sb.String()
}
