package tor

import (
	"fmt"
	"strings"
	"tuxproxy/internal/config"
)

// TorrcOptions contains advanced tuning options for Tor configuration
type TorrcOptions struct {
	DataDir           string
	BindAddress       string // e.g. "127.0.0.1" or "10.200.1.1"
	SocksPort         int
	HTTPPort          int
	DNSPort           int
	ControlPort       int    // TCP ControlPort (0 if disabled)
	ControlSocketPath string // Path to Unix domain socket
	CookieAuthFile    string // Path to cookie file for authentication
	UseCookieAuth     bool   // Enable CookieAuthentication 1
}

// BuildTorrc generates a hardened, zero-leak torrc configuration string (backward-compatible)
func BuildTorrc(cfg *config.Config, dataDir string, socksPort, httpPort, dnsPort, controlPort int) string {
	return BuildTorrcWithOptions(cfg, TorrcOptions{
		DataDir:       dataDir,
		BindAddress:   "127.0.0.1",
		SocksPort:     socksPort,
		HTTPPort:      httpPort,
		DNSPort:       dnsPort,
		ControlPort:   controlPort,
		UseCookieAuth: false,
	})
}

// BuildTorrcWithOptions generates a hardened, zero-leak torrc configuration string
func BuildTorrcWithOptions(cfg *config.Config, opts TorrcOptions) string {
	var sb strings.Builder

	bind := opts.BindAddress
	if bind == "" {
		bind = "127.0.0.1"
	}

	sb.WriteString("# Auto-generated by TuxProxy - Strict OPSEC Tor configuration\n")
	sb.WriteString(fmt.Sprintf("DataDirectory %s\n", opts.DataDir))
	sb.WriteString("AvoidDiskWrites 1\n")
	sb.WriteString("Log notice stdout\n\n")

	// Listener Ports with stream isolation (bound strictly to bind address, never 0.0.0.0)
	sb.WriteString("# Local Proxy Listeners\n")
	if opts.SocksPort > 0 {
		sb.WriteString(fmt.Sprintf("SocksPort %s:%d IsolateDestAddr IsolateDestPort\n", bind, opts.SocksPort))
	}
	if opts.HTTPPort > 0 {
		sb.WriteString(fmt.Sprintf("HTTPTunnelPort %s:%d IsolateDestAddr IsolateDestPort\n", bind, opts.HTTPPort))
	}
	if opts.DNSPort > 0 {
		sb.WriteString(fmt.Sprintf("DNSPort %s:%d\n", bind, opts.DNSPort))
	}

	// Control Interface: prefer Unix domain socket over TCP
	if opts.ControlSocketPath != "" {
		sb.WriteString(fmt.Sprintf("ControlSocket %s GroupWritable 0\n", opts.ControlSocketPath))
	} else if opts.ControlPort > 0 {
		sb.WriteString(fmt.Sprintf("ControlPort %s:%d\n", bind, opts.ControlPort))
	}

	// Cookie Authentication
	if opts.UseCookieAuth {
		sb.WriteString("CookieAuthentication 1\n")
		if opts.CookieAuthFile != "" {
			sb.WriteString(fmt.Sprintf("CookieAuthFile %s\n", opts.CookieAuthFile))
		}
	}
	sb.WriteString("\n")

	// Privacy & Zero-Leak Hardening
	sb.WriteString("# OPSEC & Zero-Leak Hardening\n")
	if cfg.SafeLogging {
		sb.WriteString("SafeLogging 1\n")
	} else {
		sb.WriteString("SafeLogging 0\n")
	}

	if cfg.DisableIPv6 {
		// Prevent dual-stack IPv6 DNS or socket leaks
		sb.WriteString("ClientUseIPv6 0\n")
		sb.WriteString("ClientPreferIPv6ORPort 0\n")
	}

	// Geolocation & Exit Node routing
	country := strings.ToLower(strings.TrimSpace(cfg.ExitCountry))
	if country != "" && country != "any" {
		sb.WriteString("\n# Geo-IP Exit Node Enforcement\n")
		sb.WriteString(fmt.Sprintf("ExitNodes {%s}\n", country))
		if cfg.StrictNodes {
			sb.WriteString("StrictNodes 1\n")
		} else {
			sb.WriteString("StrictNodes 0\n")
		}
	}

	if strings.TrimSpace(cfg.ExcludeNodes) != "" {
		sb.WriteString(fmt.Sprintf("ExcludeNodes %s\n", strings.TrimSpace(cfg.ExcludeNodes)))
		sb.WriteString(fmt.Sprintf("ExcludeExitNodes %s\n", strings.TrimSpace(cfg.ExcludeNodes)))
	}

	if cfg.NumEntryGuards > 0 {
		sb.WriteString(fmt.Sprintf("NumEntryGuards %d\n", cfg.NumEntryGuards))
	}

	// Bridges and Pluggable Transports
	bridgeType := strings.ToLower(strings.TrimSpace(cfg.BridgeType))
	if bridgeType != "" && bridgeType != "none" {
		sb.WriteString("\n# Pluggable Transports & Anti-Censorship Bridges\n")
		sb.WriteString("UseBridges 1\n")

		switch bridgeType {
		case "snowflake":
			snowflakeBin := cfg.SnowflakePath
			if snowflakeBin == "" {
				snowflakeBin = "/usr/bin/snowflake-client"
			}
			brokerURL := cfg.SnowflakeURL
			if brokerURL == "" {
				brokerURL = "https://snowflake-broker.torproject.net/"
			}
			front := cfg.SnowflakeFront
			if front == "" {
				front = "www.google.com"
			}
			ampCache := cfg.SnowflakeAMPCache
			if ampCache == "" {
				ampCache = "https://cdn.ampproject.org/"
			}

			iceServers := "stun:stun.l.google.com:19302,stun:stun.voip.blackberry.com:3478"
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin snowflake exec %s -url %s -front %s -ampcache %s -ice %s\n",
				snowflakeBin, brokerURL, front, ampCache, iceServers))

			// Include standard Snowflake bridges
			for _, br := range config.DefaultSnowflakeBridges {
				sb.WriteString(fmt.Sprintf("%s\n", br))
			}
			// Append user custom bridges if provided
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
				}
			}

		case "obfs4":
			lyrebirdBin := cfg.LyrebirdPath
			if lyrebirdBin == "" {
				lyrebirdBin = "/home/djanki/.local/bin/lyrebird"
			}
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin obfs4 exec %s\n", lyrebirdBin))
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}

		case "webtunnel":
			webtunnelBin := cfg.WebTunnelPath
			if webtunnelBin == "" {
				webtunnelBin = "/usr/local/bin/webtunnel-client"
			}
			sb.WriteString(fmt.Sprintf("ClientTransportPlugin webtunnel exec %s\n", webtunnelBin))
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}

		case "custom":
			for _, br := range cfg.CustomBridges {
				if strings.TrimSpace(br) != "" {
					if !strings.HasPrefix(strings.TrimSpace(br), "Bridge ") {
						sb.WriteString(fmt.Sprintf("Bridge %s\n", strings.TrimSpace(br)))
					} else {
						sb.WriteString(fmt.Sprintf("%s\n", strings.TrimSpace(br)))
					}
				}
			}
		}
	}

	return sb.String()
}
